import type { EndpointMetadata } from "@/contracts/http/endpointTypes";
import { API_BASE_PATH } from "@/contracts/http/versioning";
import type { IAnalyticsApi } from "@/features/analytics/api/IAnalyticsApi";

type AnalyticsOperation = Exclude<keyof IAnalyticsApi, "connectLiveAgentSessionsSocket">;

const COMMON_QUERY_ERRORS: EndpointMetadata["errorResponses"] = [
  { status: 400, code: "VALIDATION_FAILED", description: "Invalid request fields." },
  { status: 401, code: "UNAUTHORIZED", description: "Missing or invalid auth credentials." },
  { status: 403, code: "FORBIDDEN", description: "Caller cannot access this org." },
  { status: 500, code: "INTERNAL_ERROR", description: "Unexpected server error." },
] as const;

const COMMON_MUTATION_ERRORS: EndpointMetadata["errorResponses"] = [
  ...COMMON_QUERY_ERRORS,
  { status: 409, code: "CONFLICT", description: "Write conflict or duplicate entity." },
] as const;

export const analyticsEndpointRegistry: Record<AnalyticsOperation, EndpointMetadata> = {
  getOverview: {
    operationId: "analytics.getOverview",
    feature: "analytics",
    summary: "Get overview KPIs and trends.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/analytics/overview`,
    requestType: "AnalyticsFilters",
    responseType: "OverviewResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getUsage: {
    operationId: "analytics.getUsage",
    feature: "analytics",
    summary: "Get seat and active user usage analytics.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/analytics/usage`,
    requestType: "AnalyticsFilters",
    responseType: "UsageResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getOutcomes: {
    operationId: "analytics.getOutcomes",
    feature: "analytics",
    summary: "Get PR/test outcome analytics.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/analytics/outcomes`,
    requestType: "AnalyticsFilters",
    responseType: "OutcomesResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getCost: {
    operationId: "analytics.getCost",
    feature: "analytics",
    summary: "Get cost and budget analytics.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/analytics/cost`,
    requestType: "AnalyticsFilters",
    responseType: "CostResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getReliability: {
    operationId: "analytics.getReliability",
    feature: "analytics",
    summary: "Get reliability and failure analytics.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/analytics/reliability`,
    requestType: "AnalyticsFilters",
    responseType: "ReliabilityResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getGovernance: {
    operationId: "analytics.getGovernance",
    feature: "analytics",
    summary: "Get governance, policy, and seat analytics.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/analytics/governance`,
    requestType: "AnalyticsFilters",
    responseType: "GovernanceResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getAgentsHub: {
    operationId: "analytics.getAgentsHub",
    feature: "analytics",
    summary: "Get agent reliability and project breakdown metrics.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/analytics/agents-hub`,
    requestType: "AnalyticsFilters",
    responseType: "AgentsHubResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getSearchSuggestions: {
    operationId: "analytics.getSearchSuggestions",
    feature: "analytics",
    summary: "Get cross-entity search suggestions.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/search/suggestions`,
    requestType: "SearchSuggestionsRequest",
    responseType: "SearchSuggestionsResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getAgentDetail: {
    operationId: "analytics.getAgentDetail",
    feature: "analytics",
    summary: "Get detail view model for an agent.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/agents/{agentId}`,
    requestType: "GetAgentDetailRequest",
    responseType: "AgentDetailResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getProjectDetail: {
    operationId: "analytics.getProjectDetail",
    feature: "analytics",
    summary: "Get detail view model for a project.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/projects/{projectId}`,
    requestType: "GetProjectDetailRequest",
    responseType: "ProjectDetailResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getTeamDetail: {
    operationId: "analytics.getTeamDetail",
    feature: "analytics",
    summary: "Get detail view model for a team.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/teams/{teamId}`,
    requestType: "GetTeamDetailRequest",
    responseType: "TeamDetailResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getHumanDetail: {
    operationId: "analytics.getHumanDetail",
    feature: "analytics",
    summary: "Get detail view model for a human user.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/humans/{humanId}`,
    requestType: "GetHumanDetailRequest",
    responseType: "HumanDetailResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getRunDetail: {
    operationId: "analytics.getRunDetail",
    feature: "analytics",
    summary: "Get detail view model for a run.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/runs/{runId}`,
    requestType: "GetRunDetailRequest",
    responseType: "RunDetailResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  getRuleDetail: {
    operationId: "analytics.getRuleDetail",
    feature: "analytics",
    summary: "Get detail view model for a governance rule.",
    method: "GET",
    path: `${API_BASE_PATH}/orgs/{orgId}/governance/rules/{ruleId}`,
    requestType: "GetRuleDetailRequest",
    responseType: "RuleDetailResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_QUERY_ERRORS,
  },
  updateRule: {
    operationId: "analytics.updateRule",
    feature: "analytics",
    summary: "Update governance rule metadata and assignments.",
    method: "PATCH",
    path: `${API_BASE_PATH}/orgs/{orgId}/governance/rules/{ruleId}`,
    requestType: "UpdateRuleRequest",
    responseType: "UpdateRuleResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_MUTATION_ERRORS,
  },
  createComplianceRule: {
    operationId: "analytics.createComplianceRule",
    feature: "analytics",
    summary: "Create a governance compliance rule.",
    method: "POST",
    path: `${API_BASE_PATH}/orgs/{orgId}/governance/rules`,
    requestType: "CreateComplianceRuleRequest",
    responseType: "CreateComplianceRuleResponse",
    successStatus: 201,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_MUTATION_ERRORS,
  },
  createSeat: {
    operationId: "analytics.createSeat",
    feature: "analytics",
    summary: "Create a human seat user.",
    method: "POST",
    path: `${API_BASE_PATH}/orgs/{orgId}/seats`,
    requestType: "CreateSeatRequest",
    responseType: "CreateSeatResponse",
    successStatus: 201,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_MUTATION_ERRORS,
  },
  createProject: {
    operationId: "analytics.createProject",
    feature: "analytics",
    summary: "Create a project.",
    method: "POST",
    path: `${API_BASE_PATH}/orgs/{orgId}/projects`,
    requestType: "CreateProjectRequest",
    responseType: "CreateProjectResponse",
    successStatus: 201,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_MUTATION_ERRORS,
  },
  createTeam: {
    operationId: "analytics.createTeam",
    feature: "analytics",
    summary: "Create a team.",
    method: "POST",
    path: `${API_BASE_PATH}/orgs/{orgId}/teams`,
    requestType: "CreateTeamRequest",
    responseType: "CreateTeamResponse",
    successStatus: 201,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_MUTATION_ERRORS,
  },
  createAgent: {
    operationId: "analytics.createAgent",
    feature: "analytics",
    summary: "Create an agent.",
    method: "POST",
    path: `${API_BASE_PATH}/orgs/{orgId}/agents`,
    requestType: "CreateAgentRequest",
    responseType: "CreateAgentResponse",
    successStatus: 201,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_MUTATION_ERRORS,
  },
  updateAgentDescription: {
    operationId: "analytics.updateAgentDescription",
    feature: "analytics",
    summary: "Update an agent description.",
    method: "PATCH",
    path: `${API_BASE_PATH}/orgs/{orgId}/agents/{agentId}/description`,
    requestType: "UpdateAgentDescriptionRequest",
    responseType: "UpdateAgentDescriptionResponse",
    successStatus: 200,
    auth: "bearer",
    tenantScoped: true,
    errorResponses: COMMON_MUTATION_ERRORS,
  },
};
