export interface WebHtmlTemplateTokens {
  langIsoCode: string;
  webTitle: string;
}

const DEFAULT_TEMPLATE_TOKENS: WebHtmlTemplateTokens = {
  langIsoCode: "%LANG_ISO_CODE%",
  webTitle: "%WEB_TITLE%",
};

/**
 * Source-of-truth HTML template for Expo web.
 * Expo replaces placeholder tokens like %WEB_TITLE% at build time.
 */
export function buildIndexHtml(tokens: WebHtmlTemplateTokens = DEFAULT_TEMPLATE_TOKENS): string {
  const { langIsoCode, webTitle } = tokens;

  return `<!-- Generated by scripts/web/generate-index-html.ts. Run \`npm run generate:web-html\` to update. -->
<!DOCTYPE html>
<html lang="${langIsoCode}">
  <head>
    <meta charset="utf-8" />
    <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>${webTitle}</title>
    <!-- The \`react-native-web\` recommended style reset: https://necolas.github.io/react-native-web/docs/setup/#root-element -->
    <style id="expo-reset">
      /* These styles make the body full-height */
      html,
      body {
        height: 100%;
        background-color: #0a0a0a;
      }
      /* These styles disable body scrolling if you are using <ScrollView> */
      body {
        overflow: hidden;
      }
      /* These styles make the root element full-height */
      #root {
        display: flex;
        height: 100%;
        flex: 1;
        background-color: #0a0a0a;
      }
    </style>
  </head>

  <body>
    <!-- Use static rendering with Expo Router to support running without JavaScript. -->
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
    <!-- The root element for your Expo app. -->
    <div id="root"></div>
  </body>
</html>`;
}
